[build]
  command = "npm run build:cloudflare"
  publish = "out"

[[redirects]]
  from = "/hospitals/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/hospitals/*"
  to = "/api/hospitals/:splat/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.1" 