# Cloudflare Pages configuration
[build]
command = "npm run build"
output_directory = "out"

[build.environment]
NODE_VERSION = "20.11.1"
NPM_VERSION = "10.2.4"
NODE_OPTIONS = "--max-old-space-size=3072" 