name = "galeon-community-hospital-map"
compatibility_date = "2023-10-30"
pages_build_output_dir = "out"

# Commande de build
[build]
command = "bash ./build.sh"

# Suppression des champs obsolètes
# type, account_id, workers_dev, route, zone_id, [build.upload], [env.production] 