name = "galeon-community-hospital-map"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"
main = "_worker.js"

[site]
bucket = "./out"
entry-point = "functions"

[build]
command = "npm install && npm run build"

[build.upload]
format = "directory"

[env.production]
pages_build_output_dir = "out" 