# Configuration Wrangler pour Cloudflare Pages
name = "map-galeon-community"

# Configuration commune
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Spécifier le répertoire de sortie pour Next.js
pages_build_output_dir = "out"

# Configuration pour l'environnement de prévisualisation
[env.preview]
vars = { ENVIRONMENT = "development" }

# Configuration pour l'environnement de production
[env.production]
vars = { ENVIRONMENT = "production" }

# Configuration des en-têtes HTTP
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Permissions-Policy = "geolocation=(self \"https://*.galeon.community\" \"https://*.cloudflareaccess.com\")"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "upgrade-insecure-requests" 