name = "galeon-community-hospital-map"
compatibility_date = "2023-10-30"
main = "_worker.js"
pages_build_output_dir = "out"

[site]
bucket = "./out"

[build]
command = "bash ./build.sh"

# Suppression des champs obsolètes
# type, account_id, workers_dev, route, zone_id, [build.upload], [env.production] 