name = "galeon-community-hospital-map"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"

[site]
bucket = "./out"
entry-point = "functions"

[build]
command = "npm run build:cloudflare" 