// File: app/api/images/hospitals/data.ts
import { z } from 'zod';

// Hospital schema validation
export const HospitalSchema = z.object({
  id: z.string(),
  name: z.string(),
  nameEn: z.string(),
  nameFr: z.string(),
  status: z.enum(['Deployed', 'Signed']),
  deploymentDate: z.string(),
  website: z.string().url(),
  coordinates: z.tuple([z.number(), z.number()]),
  address: z.string(),
  imageUrl: z.string(),
});

export type Hospital = z.infer<typeof HospitalSchema>;

// Schema for an array of hospitals
export const HospitalsSchema = z.array(HospitalSchema);
export type Hospitals = z.infer<typeof HospitalsSchema>;

// Sample data - in production this would come from a database
export const hospitals: Hospital[] = [
  {
    id: '1',
    name: 'Centre Hospitalier de Châlon-sur-Saone',
    nameEn: 'Châlon-sur-Saone Hospital Center',
    nameFr: 'Centre Hospitalier de Châlon-sur-Saone',
    status: 'Deployed',
    deploymentDate: '2023-06-15',
    website: 'https://www.ch-chalon71.fr',
    coordinates: [4.8557, 46.7808],
    address: 'Châlon-sur-Saône, France',
    imageUrl: '/images/hospitals/chalon.png',
  },
  {
    id: '2',
    name: 'Centre Hospitalier de Toulon',
    nameEn: 'Toulon Hospital Center',
    nameFr: 'Centre Hospitalier de Toulon',
    status: 'Deployed',
    deploymentDate: '2023-09-20',
    website: 'https://www.ch-toulon.fr',
    coordinates: [5.9333, 43.1167],
    address: 'Toulon, France',
    imageUrl: '/images/hospitals/toulon.png',
  },
  {
    id: '3',
    name: 'Centre Hospitalier de Hyères',
    nameEn: 'Hyères Hospital Center',
    nameFr: 'Centre Hospitalier de Hyères',
    status: 'Deployed',
    deploymentDate: '2023-08-15',
    website: 'https://www.ch-hyeres.fr',
    coordinates: [6.1292, 43.1206],
    address: 'Hyères, France',
    imageUrl: '/images/hospitals/hyeres.png',
  },
  {
    id: '4',
    name: 'Centre Hospitalier Universitaire de Caen Normandie',
    nameEn: 'Caen Normandy University Hospital Center',
    nameFr: 'Centre Hospitalier Universitaire de Caen Normandie',
    status: 'Deployed',
    deploymentDate: '2023-07-10',
    website: 'https://www.chu-caen.fr',
    coordinates: [-0.3707, 49.1829],
    address: 'Caen, France',
    imageUrl: '/images/hospitals/caen.png',
  },
  {
    id: '5',
    name: 'Centre Hospitalier Sud Francilien',
    nameEn: 'South Francilian Hospital Center',
    nameFr: 'Centre Hospitalier Sud Francilien',
    status: 'Deployed',
    deploymentDate: '2023-11-05',
    website: 'https://www.chsf.fr',
    coordinates: [2.4702, 48.6142],
    address: 'Corbeil-Essonnes, France',
    imageUrl: '/images/hospitals/corbeil.png',
  },
  {
    id: '6',
    name: 'Groupe Hospitalier Nord-Essonne - Site de Longjumeau',
    nameEn: 'North-Essonne Hospital Group - Longjumeau Site',
    nameFr: 'Groupe Hospitalier Nord-Essonne - Site de Longjumeau',
    status: 'Deployed',
    deploymentDate: '2024-02-01',
    website: 'https://www.gh-nord-essonne.fr',
    coordinates: [2.2950, 48.6953],
    address: 'Longjumeau, France',
    imageUrl: '/images/hospitals/longjumeau.png',
  },
  {
    id: '7',
    name: 'Groupe Hospitalier Nord-Essonne - Site d\'Orsay',
    nameEn: 'North-Essonne Hospital Group - Orsay Site',
    nameFr: 'Groupe Hospitalier Nord-Essonne - Site d\'Orsay',
    status: 'Deployed',
    deploymentDate: '2024-02-01',
    website: 'https://www.gh-nord-essonne.fr',
    coordinates: [2.1818, 48.7019],
    address: 'Orsay, France',
    imageUrl: '/images/hospitals/orsay.png',
  },
  {
    id: '8',
    name: 'Centre Hospitalier Jean Leclaire',
    nameEn: 'Jean Leclaire Hospital Center',
    nameFr: 'Centre Hospitalier Jean Leclaire',
    status: 'Deployed',
    deploymentDate: '2023-08-20',
    website: 'https://www.ch-sarlat.fr',
    coordinates: [1.2167, 44.8883],
    address: 'Sarlat, France',
    imageUrl: '/images/hospitals/sarlat.png',
  },
  {
    id: '9',
    name: 'Centre Hospitalier Samuel Pozzi',
    nameEn: 'Samuel Pozzi Hospital Center',
    nameFr: 'Centre Hospitalier Samuel Pozzi',
    status: 'Deployed',
    deploymentDate: '2023-10-15',
    website: 'https://www.ch-bergerac.fr',
    coordinates: [0.4830, 44.8511],
    address: 'Bergerac, France',
    imageUrl: '/images/hospitals/bergerac.png',
  },
  {
    id: '10',
    name: 'Centre Hospitalier de Périgueux',
    nameEn: 'Périgueux Hospital Center',
    nameFr: 'Centre Hospitalier de Périgueux',
    status: 'Deployed',
    deploymentDate: '2023-07-01',
    website: 'https://www.ch-perigueux.fr',
    coordinates: [0.7167, 45.1833],
    address: 'Périgueux, France',
    imageUrl: '/images/hospitals/perigueux.png',
  },
  {
    id: '11',
    name: 'Les Bluets',
    nameEn: 'Les Bluets',
    nameFr: 'Les Bluets',
    status: 'Deployed',
    deploymentDate: '2023-12-01',
    website: 'https://www.bluets.org',
    coordinates: [2.3902, 48.8489],
    address: 'Paris, France',
    imageUrl: '/images/hospitals/bluets.png',
  },
  {
    id: '12',
    name: 'Centre Hospitalier de Montceau',
    nameEn: 'Montceau Hospital Center',
    nameFr: 'Centre Hospitalier de Montceau',
    status: 'Deployed',
    deploymentDate: '2023-05-15',
    website: 'https://www.ch-montceau71.fr',
    coordinates: [4.3659, 46.6709],
    address: 'Montceau-les-Mines, France',
    imageUrl: '/images/hospitals/montceau.png',
  },
  {
    id: '13',
    name: 'Centre Hospitalier d\'Autun',
    nameEn: 'Autun Hospital Center',
    nameFr: 'Centre Hospitalier d\'Autun',
    status: 'Deployed',
    deploymentDate: '2023-11-20',
    website: 'https://www.ch-autun.fr',
    coordinates: [4.2994, 46.9511],
    address: 'Autun, France',
    imageUrl: '/images/hospitals/autun.png',
  },
  {
    id: '14',
    name: 'CHU de Rouen',
    nameEn: 'Rouen University Hospital',
    nameFr: 'CHU de Rouen',
    status: 'Deployed',
    deploymentDate: '2023-06-01',
    website: 'https://www.chu-rouen.fr',
    coordinates: [1.1153, 49.4431],
    address: 'Rouen, France',
    imageUrl: '/images/hospitals/rouen.png',
  },
  {
    id: '15',
    name: 'Centre Hospitalier d\'Arpajon',
    nameEn: 'Arpajon Hospital Center',
    nameFr: 'Centre Hospitalier d\'Arpajon',
    status: 'Deployed',
    deploymentDate: '2024-03-01',
    website: 'https://www.ch-arpajon.fr',
    coordinates: [2.2456, 48.5906],
    address: 'Arpajon, France',
    imageUrl: '/images/hospitals/arpajon.png',
  },
  {
    id: '16',
    name: 'Centre Hospitalier de Sainte-Foy-la-Grande',
    nameEn: 'Sainte-Foy-la-Grande Hospital Center',
    nameFr: 'Centre Hospitalier de Sainte-Foy-la-Grande',
    status: 'Deployed',
    deploymentDate: '2023-10-01',
    website: 'https://www.ch-saintefoy.fr',
    coordinates: [0.2167, 44.8383],
    address: 'Sainte-Foy-la-Grande, France',
    imageUrl: '/images/hospitals/saintefoy.png',
  }
];