# File: .cloudflare/wrangler.toml
name = "galeon-map"
compatibility_date = "2023-12-01"

[build]
command = "npm run build:cloudflare"
publish = "out"
upload.format = "directory"

[build.environment]
NODE_VERSION = "20.11.1"
NPM_VERSION = "10.2.4"
NODE_OPTIONS = "--max-old-space-size=3072"

[site]
bucket = "out"
entry-point = "functions"
include = [".next/static/*"]
exclude = [".next/cache/**/*", "cache/**/*", "node_modules/**/*"]

[env.production]
workers_dev = false 