#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Vérifier les types TypeScript
npm run type-check

# Linter et formater le code
npm run lint:fix
npm run format

# Ajouter les fichiers formatés au commit
git add . 